YACLib: yaclib::IExecutor Class Reference
yaclib::IExecutor Class Reference abstract
#include <executor.hpp>
Public Types
enum class Type {
Custom = 0 , Inline , Strand , ThreadPool ,
SingleThread
}
Public Member Functions
virtual Type Tag () const =0
Return type of this executor.
virtual bool Submit (ITask &task) noexcept=0
Submit given task.
Public Member Functions inherited from yaclib::IRef
virtual void IncRef () noexcept=0
Increments reference counter.
virtual void DecRef () noexcept=0
Decrements reference counter.
virtual ~IRef ()=default
Detailed Description
Definition at line 9 of file executor.hpp.
Member Enumeration Documentation
Type
enum class yaclib::IExecutor::Type strong
Enumerator
Custom
Inline
Strand
ThreadPool
SingleThread
Definition at line 16 of file executor.hpp.
Member Function Documentation
Submit()
virtual bool yaclib::IExecutor::Submit (ITask & task) pure virtual noexcept
Submit given task.
This method may either submit or reject the task
This method increments reference counter if task is submitted.
Parameters
task task to execute
Returns
true if the task is submitted, false if the task is rejected
Referenced by yaclib::Run(), yaclib::detail::BaseCore::Submit(), and yaclib::Submit().
Tag()
virtual Type yaclib::IExecutor::Tag () const pure virtual
Return type of this executor.
Referenced by yaclib::Run().
The documentation for this class was generated from the following file:
include/yaclib/executor/executor.hpp