YACLib: yaclib::Future< V, E > Class Template Reference
yaclib::Future< V, E > Class Template Reference final
Provides a mechanism to access the result of async operations.
#include <future.hpp>
Public Member Functions
Future (const Future &)=delete
Future & operator= (const Future &)=delete
Future (Future &&other) noexcept=default
Future & operator= (Future &&other) noexcept=default
Future ()=default
The default constructor creates not a Valid Future.
~Future ()
If Future is Valid then call Stop.
bool Valid () const &noexcept
Check if this Future has Promise.
bool Ready () const &noexcept
Check that Result that corresponds to this Future is computed.
void Get () &=delete
void Get () const &&=delete
void GetUnsafe () &=delete
void GetUnsafe () const &&=delete
const Result< V, E > * Get () const &noexcept
Return copy of Result from Future.
Result< V, E > Get () &&noexcept
const Result< V, E > & GetUnsafe () const &noexcept
Return const ref of Result from Future.
Result< V, E > GetUnsafe () &&noexcept
void Stop () &&
Stop pipeline before current step, if possible.
void Detach () &&
Disable calling Stop in destructor.
Future && Via (IExecutorPtr executor) &&
Specify executor for continuation.
template<typename Functor >
auto Then (Functor &&f) &&
Attach the continuation functor to *this.
template<typename Functor >
auto ThenInline (Functor &&f) &&
Attach the continuation functor to *this.
template<typename Functor >
auto Then (IExecutorPtr e, Functor &&f) &&
Attach the continuation functor to *this.
template<typename Functor >
void Subscribe (Functor &&f) &&
Attach the final continuation functor to *this.
template<typename Functor >
void SubscribeInline (Functor &&f) &&
Attach the final continuation functor to *this.
template<typename Functor >
void Subscribe (IExecutorPtr e, Functor &&f) &&
Attach the final continuation functor to *this.
Future (detail::ResultCorePtr< V, E > core) noexcept
DETAIL.
detail::ResultCorePtr< V, E > & GetCore () noexcept
template<typename Functor >
auto Then (Functor &&f) &&
template<typename Functor >
auto ThenInline (Functor &&f) &&
template<typename Functor >
auto Then (IExecutorPtr e, Functor &&f) &&
template<typename Functor >
void Subscribe (Functor &&f) &&
template<typename Functor >
void SubscribeInline (Functor &&f) &&
template<typename Functor >
void Subscribe (IExecutorPtr e, Functor &&f) &&
Detailed Description
template<typename V, typename E = StopError>
class yaclib::Future< V, E >
Provides a mechanism to access the result of async operations.
Future and Promise are like a Single Producer/Single Consumer one-shot one-element channel. Use the Promise to fulfill the Future.
Examples
simple.cpp, when_all.cpp, and when_any.cpp.
Definition at line 17 of file future.hpp.
Constructor & Destructor Documentation
Future() [1/4]
template<typename V , typename E = StopError> yaclib::Future< V, E >::Future (const Future< V, E > &) delete
Future() [2/4]
template<typename V , typename E = StopError> yaclib::Future< V, E >::Future (Future< V, E > && other) default noexcept
Future() [3/4]
template<typename V , typename E = StopError> yaclib::Future< V, E >::Future () default
The default constructor creates not a Valid Future.
Needed only for usability, e.g. instead of std::optional<Future<T>> in containers.
~Future()
template<typename V , typename E > yaclib::Future< V, E >::~Future
If Future is Valid then call Stop.
Definition at line 187 of file future_impl.hpp.
Future() [4/4]
template<typename V , typename E > yaclib::Future< V, E >::Future (detail::ResultCorePtr< V, E > core) noexcept
DETAIL.
Definition at line 295 of file future_impl.hpp.
Member Function Documentation
Detach()
template<typename V , typename E = StopError> void yaclib::Future< V, E >::Detach () &&
Disable calling Stop in destructor.
Definition at line 240 of file future_impl.hpp.
Get() [1/4]
template<typename V , typename E = StopError> Result< V, E > yaclib::Future< V, E >::Get () && noexcept
Get() [2/4]
template<typename V , typename E = StopError> void yaclib::Future< V, E >::Get () & delete
Get() [3/4]
template<typename V , typename E = StopError> void yaclib::Future< V, E >::Get () const && delete
Get() [4/4]
template<typename V , typename E = StopError> const Result< V, E > * yaclib::Future< V, E >::Get () const & noexcept
Return copy of Result from Future.
If Ready is false return an empty Result. This method is thread-safe and can be called multiple times.
Note
The behavior is undefined if Valid is false before the call to this function.
Returns
Result stored in the shared state
GetCore()
template<typename V , typename E > detail::ResultCorePtr< V, E > & yaclib::Future< V, E >::GetCore noexcept
Definition at line 299 of file future_impl.hpp.
Referenced by yaclib::WaitGroup::Add(), yaclib::detail::FutureAwaiter::FutureAwaiter(), yaclib::Wait(), yaclib::WaitFor(), and yaclib::WaitUntil().
GetUnsafe() [1/4]
template<typename V , typename E = StopError> Result< V, E > yaclib::Future< V, E >::GetUnsafe () && noexcept
GetUnsafe() [2/4]
template<typename V , typename E = StopError> void yaclib::Future< V, E >::GetUnsafe () & delete
GetUnsafe() [3/4]
template<typename V , typename E = StopError> void yaclib::Future< V, E >::GetUnsafe () const && delete
GetUnsafe() [4/4]
template<typename V , typename E = StopError> const Result< V, E > & yaclib::Future< V, E >::GetUnsafe () const & noexcept
Return const ref of Result from Future.
Assume Ready is true. This method is NOT thread-safe and can be called multiple times.
Note
The behavior is undefined if Valid is false before the call to this function.
Returns
Result stored in the shared state
operator=() [1/2]
template<typename V , typename E = StopError> Future & yaclib::Future< V, E >::operator= (const Future< V, E > &) delete
operator=() [2/2]
template<typename V , typename E = StopError> Future & yaclib::Future< V, E >::operator= (Future< V, E > && other) default noexcept
Ready()
template<typename V , typename E = StopError> bool yaclib::Future< V, E >::Ready () const & noexcept
Check that Result that corresponds to this Future is computed.
Returns
false if the Result of this Future is not computed yet, otherwise true
Definition at line 199 of file future_impl.hpp.
Stop()
template<typename V , typename E = StopError> void yaclib::Future< V, E >::Stop () &&
Stop pipeline before current step, if possible.
Definition at line 234 of file future_impl.hpp.
Subscribe() [1/4]
template<typename V , typename E = StopError> template<typename Functor > void yaclib::Future< V, E >::Subscribe (Functor && f) &&
Definition at line 274 of file future_impl.hpp.
Subscribe() [2/4]
template<typename V , typename E = StopError> template<typename Functor > void yaclib::Future< V, E >::Subscribe (Functor && f) &&
Attach the final continuation functor to *this.
Note
Functor must return void type.
Parameters
f A continuation to be attached
Subscribe() [3/4]
template<typename V , typename E = StopError> template<typename Functor > void yaclib::Future< V, E >::Subscribe (IExecutorPtr e, Functor && f) &&
Definition at line 286 of file future_impl.hpp.
References yaclib::IExecutor::Inline, YACLIB_ERROR, and YACLIB_INFO.
Subscribe() [4/4]
template<typename V , typename E = StopError> template<typename Functor > void yaclib::Future< V, E >::Subscribe (IExecutorPtr e, Functor && f) &&
Attach the final continuation functor to *this.
The functor will be executed via the specified executor.
Note
The behavior is undefined if Valid is false before the call to this function.
Parameters
e Executor which will Execute the continuation
f A continuation to be attached
SubscribeInline() [1/2]
template<typename V , typename E = StopError> template<typename Functor > void yaclib::Future< V, E >::SubscribeInline (Functor && f) &&
Definition at line 280 of file future_impl.hpp.
SubscribeInline() [2/2]
template<typename V , typename E = StopError> template<typename Functor > void yaclib::Future< V, E >::SubscribeInline (Functor && f) &&
Attach the final continuation functor to *this.
The functor will be executed via Inline executor.
Note
The behavior is undefined if Valid is false before the call to this function.
Parameters
f A continuation to be attached
Then() [1/4]
template<typename V , typename E = StopError> template<typename Functor > auto yaclib::Future< V, E >::Then (Functor && f) &&
Definition at line 252 of file future_impl.hpp.
Then() [2/4]
template<typename V , typename E = StopError> template<typename Functor > auto yaclib::Future< V, E >::Then (Functor && f) &&
Attach the continuation functor to *this.
Note
The behavior is undefined if Valid is false before the call to this function.
Parameters
f A continuation to be attached
Returns
New Future object associated with the functor result
Examples
simple.cpp.
Referenced by TEST().
Then() [3/4]
template<typename V , typename E = StopError> template<typename Functor > auto yaclib::Future< V, E >::Then (IExecutorPtr e, Functor && f) &&
Definition at line 264 of file future_impl.hpp.
References yaclib::IExecutor::Inline, YACLIB_ERROR, and YACLIB_INFO.
Then() [4/4]
template<typename V , typename E = StopError> template<typename Functor > auto yaclib::Future< V, E >::Then (IExecutorPtr e, Functor && f) &&
Attach the continuation functor to *this.
The functor will be executed via the specified executor.
Note
The behavior is undefined if Valid is false before the call to this function.
Parameters
e Executor which will Execute the continuation
f A continuation to be attached
Returns
New Future object associated with the functor result
ThenInline() [1/2]
template<typename V , typename E = StopError> template<typename Functor > auto yaclib::Future< V, E >::ThenInline (Functor && f) &&
Definition at line 258 of file future_impl.hpp.
ThenInline() [2/2]
template<typename V , typename E = StopError> template<typename Functor > auto yaclib::Future< V, E >::ThenInline (Functor && f) &&
Attach the continuation functor to *this.
The functor will be executed via Inline executor.
Note
The behavior is undefined if Valid is false before the call to this function.
Parameters
f A continuation to be attached
Returns
New Future object associated with the functor result
Valid()
template<typename V , typename E = StopError> bool yaclib::Future< V, E >::Valid () const & noexcept
Check if this Future has Promise.
Returns
false if this Future is default-constructed or moved to, otherwise true
Examples
simple.cpp.
Definition at line 194 of file future_impl.hpp.
Referenced by yaclib::WaitGroup::Add(), and TEST().
Via()
template<typename V , typename E = StopError> Future< V, E > && yaclib::Future< V, E >::Via (IExecutorPtr executor) &&
Specify executor for continuation.
Definition at line 245 of file future_impl.hpp.
The documentation for this class was generated from the following files:
include/yaclib/async/future.hpp
include/yaclib/async/detail/future_impl.hpp