YACLib: yaclib::WaitGroup Class Reference
yaclib::WaitGroup Class Reference
#include <wait_group.hpp>
Public Member Functions
template<typename V , typename E >
void Add (Future< V, E > &f)
Add Future to WaitGroup.
void Wait ()
Waiting for the execution of all futures added to WaitGroup.
Detailed Description
Definition at line 13 of file wait_group.hpp.
Member Function Documentation
Add()
template<typename V , typename E > void yaclib::WaitGroup::Add (Future< V, E > & f) inline
Add Future to WaitGroup.
You can add in the Wait process only from the functors added to this WaitGroup, but we are guaranteed to wait only for those that were added from the functors that were executed before, or added to this WaitGroupx before Wait. You also can't use future before Wait
Parameters
f one futures to wait
Definition at line 24 of file wait_group.hpp.
References Add(), yaclib::Future< V, E >::GetCore(), and yaclib::Future< V, E >::Valid().
Referenced by Add().
Wait()
void yaclib::WaitGroup::Wait ()
Waiting for the execution of all futures added to WaitGroup.
Definition at line 8 of file wait_group.cpp.
The documentation for this class was generated from the following files:
include/yaclib/algo/wait_group.hpp
src/algo/wait_group.cpp