YACLib: yaclib::detail::Yielder Class Reference
yaclib::detail::Yielder Class Reference
#include <yielder.hpp>
Public Member Functions
Yielder ()
void MaybeYield ()
Static Public Member Functions
static void SetFrequency (uint32_t freq)
static void SetSleepTime (uint32_t ns)
Detailed Description
Definition at line 14 of file yielder.hpp.
Constructor & Destructor Documentation
Yielder()
yaclib::detail::Yielder::Yielder () explicit
Definition at line 13 of file yielder.cpp.
Member Function Documentation
MaybeYield()
void yaclib::detail::Yielder::MaybeYield ()
Definition at line 16 of file yielder.cpp.
Referenced by yaclib::detail::InjectFault().
SetFrequency()
void yaclib::detail::Yielder::SetFrequency (uint32_t freq) static
Definition at line 38 of file yielder.cpp.
Referenced by yaclib::SetFrequency().
SetSleepTime()
void yaclib::detail::Yielder::SetSleepTime (uint32_t ns) static
Definition at line 42 of file yielder.cpp.
Referenced by yaclib::SetSleepTime().
The documentation for this class was generated from the following files:
include/yaclib/fault/detail/yielder.hpp
src/fault/antagonist/yielder.cpp