YACLib: yaclib::detail::ResultCore< V, E > Class Template Reference
yaclib::detail::ResultCore< V, E > Class Template Reference
#include <result_core.hpp>
Public Member Functions
ResultCore () noexcept
template<typename... Args>
ResultCore (Args &&... args)
template<typename T >
void Set (T &&value) noexcept
void SetStop () final
Result< V, E > & Get () noexcept
Public Member Functions inherited from yaclib::detail::BaseCore
BaseCore (State s) noexcept
void SetExecutor (IExecutorPtr executor) noexcept
const IExecutorPtr & GetExecutor () const noexcept
void SetCallback (BaseCore &callback) noexcept
void SetCallbackInline (InlineCore &callback, bool async=false) noexcept
bool SetWait (IRef &callback) noexcept
bool ResetWait () noexcept
virtual void SetStop ()=0
void Stop () noexcept
bool Empty () const noexcept
bool Alive () const noexcept
Public Member Functions inherited from yaclib::detail::InlineCore
void Call () noexcept override
void Cancel () noexcept override
virtual void CallInline (InlineCore &, State) noexcept
virtual void Cancel () noexcept=0
virtual void Call () noexcept=0
Public Member Functions inherited from yaclib::IRef
virtual void IncRef () noexcept=0
Increments reference counter.
virtual void DecRef () noexcept=0
Decrements reference counter.
virtual ~IRef ()=default
Additional Inherited Members
Public Types inherited from yaclib::detail::InlineCore
enum class State {
Empty = 0 , HasResult , HasCallback , HasCallbackInline ,
HasAsyncCallback , HasWait , HasStop
}
Public Attributes inherited from yaclib::detail::Node
Node * next = nullptr
Protected Member Functions inherited from yaclib::detail::BaseCore
void Submit () noexcept
void Cancel () noexcept final
Protected Attributes inherited from yaclib::detail::BaseCore
yaclib_std::atomic< State > _state
IntrusivePtr< ITask > _caller
IExecutorPtr _executor
IntrusivePtr< IRef > _callback
Detailed Description
template<typename V, typename E>
class yaclib::detail::ResultCore< V, E >
Definition at line 14 of file result_core.hpp.
Constructor & Destructor Documentation
ResultCore() [1/2]
template<typename V , typename E > yaclib::detail::ResultCore< V, E >::ResultCore () inline noexcept
Definition at line 16 of file result_core.hpp.
References yaclib::detail::InlineCore::Empty.
ResultCore() [2/2]
template<typename V , typename E > template<typename... Args> yaclib::detail::ResultCore< V, E >::ResultCore (Args &&... args) inline explicit
Definition at line 20 of file result_core.hpp.
Member Function Documentation
Get()
template<typename V , typename E > Result< V, E > & yaclib::detail::ResultCore< V, E >::Get () inline noexcept
Definition at line 51 of file result_core.hpp.
Set()
template<typename V , typename E > template<typename T > void yaclib::detail::ResultCore< V, E >::Set (T && value) inline noexcept
Definition at line 24 of file result_core.hpp.
References yaclib::detail::BaseCore::_callback, yaclib::detail::BaseCore::_caller, yaclib::detail::BaseCore::_executor, yaclib::detail::BaseCore::_state, yaclib::detail::InlineCore::CallInline(), yaclib::detail::InlineCore::HasAsyncCallback, yaclib::detail::InlineCore::HasCallback, yaclib::detail::InlineCore::HasCallbackInline, yaclib::detail::InlineCore::HasResult, yaclib::detail::InlineCore::HasStop, yaclib::detail::InlineCore::HasWait, and yaclib::detail::BaseCore::Submit().
Referenced by yaclib::detail::PromiseType< V, E >::return_value(), yaclib::detail::PromiseType< void, E >::return_void(), yaclib::detail::ResultCore< V, E >::SetStop(), yaclib::detail::ResultCore< void, void >::SetStop(), yaclib::detail::PromiseType< V, E >::unhandled_exception(), and yaclib::detail::PromiseType< void, E >::unhandled_exception().
SetStop()
template<typename V , typename E > void yaclib::detail::ResultCore< V, E >::SetStop () inline final virtual
Implements yaclib::detail::BaseCore.
Definition at line 47 of file result_core.hpp.
References yaclib::detail::ResultCore< V, E >::Set().
The documentation for this class was generated from the following file:
include/yaclib/async/detail/result_core.hpp