YACLib: yaclib::detail::SharedTimedMutex Class Reference
yaclib::detail::SharedTimedMutex Class Reference
#include <shared_timed_mutex.hpp>
Public Member Functions
SharedTimedMutex ()=default
~SharedTimedMutex () noexcept=default
SharedTimedMutex (const SharedTimedMutex &)=delete
SharedTimedMutex & operator= (const SharedTimedMutex &)=delete
void lock ()
bool try_lock () noexcept
void unlock () noexcept
template<typename _Rep , typename _Period >
bool try_lock_for (const std::chrono::duration< _Rep, _Period > &duration)
template<typename _Clock , typename _Duration >
bool try_lock_until (const std::chrono::time_point< _Clock, _Duration > &duration)
void lock_shared ()
bool try_lock_shared () noexcept
void unlock_shared () noexcept
template<typename _Rep , typename _Period >
bool try_lock_shared_for (const std::chrono::duration< _Rep, _Period > &duration)
template<typename _Clock , typename _Duration >
bool try_lock_shared_until (const std::chrono::time_point< _Clock, _Duration > &duration)
Detailed Description
Definition at line 12 of file shared_timed_mutex.hpp.
Constructor & Destructor Documentation
SharedTimedMutex() [1/2]
yaclib::detail::SharedTimedMutex::SharedTimedMutex () default
~SharedTimedMutex()
yaclib::detail::SharedTimedMutex::~SharedTimedMutex () default noexcept
SharedTimedMutex() [2/2]
yaclib::detail::SharedTimedMutex::SharedTimedMutex (const SharedTimedMutex &) delete
Member Function Documentation
lock()
void yaclib::detail::SharedTimedMutex::lock ()
Definition at line 6 of file shared_timed_mutex.cpp.
References YACLIB_INJECT_FAULT.
lock_shared()
void yaclib::detail::SharedTimedMutex::lock_shared ()
Definition at line 19 of file shared_timed_mutex.cpp.
References YACLIB_INJECT_FAULT.
operator=()
SharedTimedMutex & yaclib::detail::SharedTimedMutex::operator= (const SharedTimedMutex &) delete
try_lock()
bool yaclib::detail::SharedTimedMutex::try_lock () noexcept
Definition at line 10 of file shared_timed_mutex.cpp.
References YACLIB_INJECT_FAULT.
try_lock_for()
template<typename _Rep , typename _Period > bool yaclib::detail::SharedTimedMutex::try_lock_for (const std::chrono::duration< _Rep, _Period > & duration) inline
Definition at line 25 of file shared_timed_mutex.hpp.
References try_lock_until().
try_lock_shared()
bool yaclib::detail::SharedTimedMutex::try_lock_shared () noexcept
Definition at line 23 of file shared_timed_mutex.cpp.
References YACLIB_INJECT_FAULT.
try_lock_shared_for()
template<typename _Rep , typename _Period > bool yaclib::detail::SharedTimedMutex::try_lock_shared_for (const std::chrono::duration< _Rep, _Period > & duration) inline
Definition at line 39 of file shared_timed_mutex.hpp.
References try_lock_until().
try_lock_shared_until()
template<typename _Clock , typename _Duration > bool yaclib::detail::SharedTimedMutex::try_lock_shared_until (const std::chrono::time_point< _Clock, _Duration > & duration) inline
Definition at line 43 of file shared_timed_mutex.hpp.
References YACLIB_INJECT_FAULT.
try_lock_until()
template<typename _Clock , typename _Duration > bool yaclib::detail::SharedTimedMutex::try_lock_until (const std::chrono::time_point< _Clock, _Duration > & duration) inline
Definition at line 29 of file shared_timed_mutex.hpp.
References YACLIB_INJECT_FAULT.
Referenced by try_lock_for(), and try_lock_shared_for().
unlock()
void yaclib::detail::SharedTimedMutex::unlock () noexcept
Definition at line 15 of file shared_timed_mutex.cpp.
References YACLIB_INJECT_FAULT.
unlock_shared()
void yaclib::detail::SharedTimedMutex::unlock_shared () noexcept
Definition at line 28 of file shared_timed_mutex.cpp.
References YACLIB_INJECT_FAULT.
The documentation for this class was generated from the following files:
include/yaclib/fault/detail/mutex/shared_timed_mutex.hpp
src/fault/mutex/shared_timed_mutex.cpp