YACLib: yaclib::detail::AllCombinator< V, E, N, FutureValue > Class Template Reference
yaclib::detail::AllCombinator< V, E, N, FutureValue > Class Template Reference
#include <when_all_impl.hpp>
Public Member Functions
AllCombinator (ResultCorePtr< FutureValue, E > promise, std::size_t size)
void CallInline (InlineCore &caller, State) noexcept final
void Combine (Result< V, E > &&result) noexcept
~AllCombinator () override
Public Member Functions inherited from yaclib::detail::InlineCore
void Call () noexcept override
void Cancel () noexcept override
virtual void CallInline (InlineCore &, State) noexcept
virtual void Cancel () noexcept=0
virtual void Call () noexcept=0
Public Member Functions inherited from yaclib::IRef
virtual void IncRef () noexcept=0
Increments reference counter.
virtual void DecRef () noexcept=0
Decrements reference counter.
virtual ~IRef ()=default
Static Public Member Functions
static std::pair< Future< FutureValue, E >, AllCombinator * > Make (std::size_t size)
Additional Inherited Members
Public Types inherited from yaclib::detail::InlineCore
enum class State {
Empty = 0 , HasResult , HasCallback , HasCallbackInline ,
HasAsyncCallback , HasWait , HasStop
}
Public Attributes inherited from yaclib::detail::Node
Node * next = nullptr
Detailed Description
template<typename V, typename E, std::size_t N = 0, typename FutureValue = std::conditional_t<std::is_void_v<V>, void, std::conditional_t<N != 0, std::array<V, N>, std::vector<V>>>>
class yaclib::detail::AllCombinator< V, E, N, FutureValue >
Definition at line 35 of file when_all_impl.hpp.
Constructor & Destructor Documentation
AllCombinator()
template<typename V , typename E , std::size_t N = 0, typename FutureValue = std::conditional_t<std::is_void_v<V>, void, std::conditional_t<N != 0, std::array<V, N>, std::vector<V>>>> yaclib::detail::AllCombinator< V, E, N, FutureValue >::AllCombinator (ResultCorePtr< FutureValue, E > promise, std::size_t size) inline explicit
Definition at line 52 of file when_all_impl.hpp.
~AllCombinator()
template<typename V , typename E , std::size_t N = 0, typename FutureValue = std::conditional_t<std::is_void_v<V>, void, std::conditional_t<N != 0, std::array<V, N>, std::vector<V>>>> yaclib::detail::AllCombinator< V, E, N, FutureValue >::~AllCombinator () inline override
Definition at line 82 of file when_all_impl.hpp.
References yaclib::detail::AllCombinatorBase< V >::_done.
Member Function Documentation
CallInline()
template<typename V , typename E , std::size_t N = 0, typename FutureValue = std::conditional_t<std::is_void_v<V>, void, std::conditional_t<N != 0, std::array<V, N>, std::vector<V>>>> void yaclib::detail::AllCombinator< V, E, N, FutureValue >::CallInline (InlineCore & caller, State) inline final virtual noexcept
Reimplemented from yaclib::detail::InlineCore.
Definition at line 59 of file when_all_impl.hpp.
References yaclib::detail::AllCombinatorBase< V >::_done, and yaclib::detail::AllCombinator< V, E, N, FutureValue >::Combine().
Combine()
template<typename V , typename E , std::size_t N = 0, typename FutureValue = std::conditional_t<std::is_void_v<V>, void, std::conditional_t<N != 0, std::array<V, N>, std::vector<V>>>> void yaclib::detail::AllCombinator< V, E, N, FutureValue >::Combine (Result< V, E > && result) inline noexcept
Definition at line 66 of file when_all_impl.hpp.
References yaclib::detail::AllCombinatorBase< V >::_done, yaclib::Error, yaclib::Exception, and yaclib::Value.
Referenced by yaclib::detail::AllCombinator< V, E, N, FutureValue >::CallInline().
Make()
template<typename V , typename E , std::size_t N = 0, typename FutureValue = std::conditional_t<std::is_void_v<V>, void, std::conditional_t<N != 0, std::array<V, N>, std::vector<V>>>> static std::pair< Future< FutureValue, E >, AllCombinator * > yaclib::detail::AllCombinator< V, E, N, FutureValue >::Make (std::size_t size) inline static
Definition at line 39 of file when_all_impl.hpp.
Referenced by yaclib::WhenAll().
The documentation for this class was generated from the following file:
include/yaclib/algo/detail/when_all_impl.hpp