YACLib: yaclib::detail Namespace Reference
yaclib::detail Namespace Reference
Classes
class AllCombinator
class AllCombinatorBase
class AllCombinatorBase< void >
class AnyCombinator
class AnyCombinatorBase
class AnyCombinatorBase< V, E, WhenPolicy::FirstFail >
class AnyCombinatorBase< V, E, WhenPolicy::LastFail >
struct Atomic
struct Atomic< T * >
struct AtomicBase
struct AtomicBase< T, Atomic, true >
struct AtomicCounter
class AtomicEvent
class AtomicFlag
class BaseCore
class ConditionVariable
class Core
struct CoroutineDeleter
struct DefaultDeleter
class Destroy
struct EventDeleter
class FunctorWrapper
class FutureAwaiter
struct Head
struct Head< T, Args... >
class InlineCore
struct InstantiationTypes
struct InstantiationTypes< T, T< V, E > >
struct Invoke
struct Invoke< Functor, void >
struct IsInstantiationOf
struct IsInstantiationOf< T, T< U... > >
struct IsInvocable
struct IsInvocable< Functor, void >
class List
class MPSCStack
Lock free multi-producer/single-consumer stack.
class Mutex
class MutexEvent
struct Node
Node class, used in intrusive data structure.
struct NopeCounter
struct NoTimeoutTag
struct PromiseType
struct PromiseType< void, E >
class RandomDevice
class RecursiveMutex
class RecursiveTimedMutex
class ResultCore
class ResultCore< void, void >
struct Return
struct Return< V, E, Functor, 1 >
struct Return< V, E, Functor, 2 >
struct Return< V, E, Functor, 4 >
struct Return< V, E, Functor, 8 >
class SafeCall
class SharedMutex
class SharedTimedMutex
struct SteadyClock
class SuspendCondition
struct SystemClock
class Thread
class TimedMutex
class UniqueTask
class Yielder
Typedefs
using DefaultEvent = MutexEvent
template<CoreType Type, typename V , typename E >
using ResultCoreT = std::conditional_t< Type==CoreType::Subscribe, ResultCore< void, void >, ResultCore< V, E > >
template<typename V , typename E >
using ResultCorePtr = IntrusivePtr< ResultCore< V, E > >
Enumerations
enum class CoreType { Run , Then , Subscribe }
Functions
template<typename Event , typename Timeout , typename Range >
bool WaitRange (const Timeout &timeout, const Range &range, std::size_t count)
template<typename Event , typename Timeout , typename... Cores>
bool WaitCore (const Timeout &timeout, Cores &... cores)
template<typename Event , typename Timeout , typename Iterator >
bool WaitIterator (const Timeout &timeout, Iterator it, std::size_t size)
template bool WaitCore< MutexEvent, NoTimeoutTag, BaseCore > (const NoTimeoutTag &, BaseCore &)
template<typename Combinator , typename It >
void WhenImpl (Combinator *combinator, It it, std::size_t size)
template<typename Combinator , typename... V, typename... E>
void WhenImpl (Combinator *combinator, Future< V, E > &&... futures)
template<typename V , typename E , typename Functor >
constexpr int Tag ()
template<CoreType Type, typename Arg , typename E , typename Functor >
auto * MakeCore (Functor &&f)
template<CoreType Type, bool Inline, typename Arg , typename E , typename Functor >
auto SetCallback (ResultCorePtr< Arg, E > caller, Functor &&f)
template<typename Functor >
ITask * MakeUniqueTask (Functor &&functor)
Yielder * GetYielder ()
void InjectFault ()
Variables
const Thread::id kInvalidThreadId = std::thread::id{}
constexpr int kFreq = 16
constexpr int kSleepTimeNs = 200
Typedef Documentation
DefaultEvent
using yaclib::detail::DefaultEvent = typedef MutexEvent
Definition at line 87 of file wait_impl.hpp.
ResultCorePtr
template<typename V , typename E > using yaclib::detail::ResultCorePtr = typedef IntrusivePtr<ResultCore<V, E> >
Definition at line 78 of file result_core.hpp.
ResultCoreT
template<CoreType Type, typename V , typename E > using yaclib::detail::ResultCoreT = typedef std::conditional_t<Type == CoreType::Subscribe, ResultCore<void, void>, ResultCore<V, E> >
Definition at line 15 of file core.hpp.
Enumeration Type Documentation
CoreType
enum class yaclib::detail::CoreType strong
Enumerator
Run
Then
Subscribe
Definition at line 8 of file core.hpp.
Function Documentation
GetYielder()
Yielder * yaclib::detail::GetYielder ()
Definition at line 6 of file inject_fault.cpp.
Referenced by InjectFault().
InjectFault()
void yaclib::detail::InjectFault ()
Definition at line 11 of file inject_fault.cpp.
References GetYielder(), and yaclib::detail::Yielder::MaybeYield().
MakeCore()
template<CoreType Type, typename Arg , typename E , typename Functor > auto * yaclib::detail::MakeCore (Functor && f)
Definition at line 153 of file future_impl.hpp.
References Run, Subscribe, and Then.
MakeUniqueTask()
template<typename Functor > ITask * yaclib::detail::MakeUniqueTask (Functor && functor)
Definition at line 29 of file unique_task.hpp.
Referenced by yaclib::Submit().
SetCallback()
template<CoreType Type, bool Inline, typename Arg , typename E , typename Functor > auto yaclib::detail::SetCallback (ResultCorePtr< Arg, E > caller, Functor && f)
Definition at line 169 of file future_impl.hpp.
References Run, and Then.
Tag()
template<typename V , typename E , typename Functor > constexpr int yaclib::detail::Tag () constexpr
Definition at line 13 of file future_impl.hpp.
WaitCore()
template<typename Event , typename Timeout , typename... Cores> bool yaclib::detail::WaitCore (const Timeout & timeout, Cores &... cores)
Definition at line 53 of file wait_impl.hpp.
WaitCore< MutexEvent, NoTimeoutTag, BaseCore >()
template bool yaclib::detail::WaitCore< MutexEvent, NoTimeoutTag, BaseCore > (const NoTimeoutTag & , BaseCore &)
WaitIterator()
template<typename Event , typename Timeout , typename Iterator > bool yaclib::detail::WaitIterator (const Timeout & timeout, Iterator it, std::size_t size)
Definition at line 63 of file wait_impl.hpp.
WaitRange()
template<typename Event , typename Timeout , typename Range > bool yaclib::detail::WaitRange (const Timeout & timeout, const Range & range, std::size_t count)
Definition at line 23 of file wait_impl.hpp.
References yaclib::detail::BaseCore::Empty(), yaclib::detail::BaseCore::ResetWait(), and yaclib::detail::BaseCore::SetWait().
WhenImpl() [1/2]
template<typename Combinator , typename... V, typename... E> void yaclib::detail::WhenImpl (Combinator * combinator, Future< V, E > &&... futures)
Definition at line 22 of file when_impl.hpp.
WhenImpl() [2/2]
template<typename Combinator , typename It > void yaclib::detail::WhenImpl (Combinator * combinator, It it, std::size_t size)
Definition at line 13 of file when_impl.hpp.
Referenced by yaclib::WhenAll(), and yaclib::WhenAny().
Variable Documentation
kFreq
constexpr int yaclib::detail::kFreq = 16 inline constexpr
Definition at line 6 of file yielder.cpp.
kInvalidThreadId
const Thread::id yaclib::detail::kInvalidThreadId = std::thread::id{}
Definition at line 48 of file thread.cpp.
kSleepTimeNs
constexpr int yaclib::detail::kSleepTimeNs = 200 inline constexpr
Definition at line 7 of file yielder.cpp.