YACLib: yaclib Namespace Reference
yaclib Namespace Reference
Namespaces
namespace detail
Classes
class Future
Provides a mechanism to access the result of async operations.
class IExecutor
class IFunc
Shared callable interface.
class Inline
class IntrusivePtr
A intrusive pointer to objects with an embedded reference count.
class IRef
Reference counting interface.
class ITask
Callable that can be executed in an IExecutor.
class IThread
class IThreadFactory
class IThreadPool
Interface for thread-pool-like executors.
struct NoRefTag
class Promise
class Result
Encapsulated return value from caller.
struct ResultEmpty
class ResultError
struct StopError
Default error.
struct StopTag
struct Unit
For internal instead of void usage.
class WaitGroup
Typedefs
template<typename V , typename E >
using Contract = std::pair< Future< V, E >, Promise< V, E > >
Describes channel with future and promise.
using IExecutorPtr = IntrusivePtr< IExecutor >
using IThreadPtr = IThread *
using IThreadFactoryPtr = IntrusivePtr< IThreadFactory >
using IThreadPoolPtr = IntrusivePtr< IThreadPool >
using LogCallback = void(*)(std::string_view file, std::size_t line, std::string_view function, std::string_view condition, std::string_view message)
using IFuncPtr = IntrusivePtr< IFunc >
template<typename... Args>
using head_t = typename detail::Head< Args... >::Type
template<typename Functor , typename... Arg>
using invoke_t = typename detail::Invoke< Functor, Arg... >::Type
template<typename T >
using result_value_t = typename detail::InstantiationTypes< Result, T >::Value
template<typename T >
using result_error_t = typename detail::InstantiationTypes< Result, T >::Error
template<typename T >
using future_value_t = typename detail::InstantiationTypes< Future, T >::Value
template<typename T >
using future_error_t = typename detail::InstantiationTypes< Future, T >::Error
Enumerations
enum class WhenPolicy { None , FirstFail , LastFail }
This Policy describe how When* algorithm interpret if Future will be fulfilled by error or exception.
enum class ResultState : char { Value = 0 , Exception = 1 , Error = 2 , Empty = 3 }
Functions
template<typename Event = detail::DefaultEvent, typename... V, typename... E>
void Wait (Future< V, E > &... fs)
Wait until Ready becomes true.
template<typename Event = detail::DefaultEvent, typename It >
std::enable_if_t<!is_future_v< It >, void > Wait (It begin, It end)
Wait until Ready becomes true.
template<typename Event = detail::DefaultEvent, typename It >
void Wait (It begin, std::size_t size)
Wait until Ready becomes true.
template<typename Event = detail::MutexEvent, typename Rep , typename Period , typename... V, typename... E>
bool WaitFor (const std::chrono::duration< Rep, Period > &timeout_duration, Future< V, E > &... fs)
Wait until the specified timeout duration has elapsed or Ready becomes true.
template<typename Event = detail::MutexEvent, typename Rep , typename Period , typename Iterator >
std::enable_if_t<!is_future_v< Iterator >, bool > WaitFor (const std::chrono::duration< Rep, Period > &timeout_duration, Iterator begin, Iterator end)
Wait until the specified timeout duration has elapsed or Ready becomes true.
template<typename Event = detail::MutexEvent, typename Rep , typename Period , typename Iterator >
bool WaitFor (const std::chrono::duration< Rep, Period > &timeout_duration, Iterator begin, std::size_t size)
Wait until the specified timeout duration has elapsed or Ready becomes true.
template<typename Event = detail::MutexEvent, typename Clock , typename Duration , typename... V, typename... E>
bool WaitUntil (const std::chrono::time_point< Clock, Duration > &timeout_time, Future< V, E > &... fs)
Wait until specified time has been reached or Ready becomes true.
template<typename Event = detail::MutexEvent, typename Clock , typename Duration , typename Iterator >
std::enable_if_t<!is_future_v< Iterator >, bool > WaitUntil (const std::chrono::time_point< Clock, Duration > &timeout_time, Iterator begin, Iterator end)
Wait until specified time has been reached or Ready becomes true.
template<typename Event = detail::MutexEvent, typename Clock , typename Duration , typename Iterator >
bool WaitUntil (const std::chrono::time_point< Clock, Duration > &timeout_time, Iterator begin, std::size_t size)
Wait until specified time has been reached or Ready becomes true.
template<WhenPolicy P = WhenPolicy::FirstFail, typename It , typename T = typename std::iterator_traits<It>::value_type>
auto WhenAll (It begin, std::size_t size)
Create Future which will be ready when all futures are ready.
template<WhenPolicy P = WhenPolicy::FirstFail, typename It , typename T = typename std::iterator_traits<It>::value_type>
auto WhenAll (It begin, It end)
Create Future which will be ready when all futures are ready.
template<WhenPolicy P = WhenPolicy::FirstFail, typename V , typename E , typename... Vs, typename... Es>
auto WhenAll (Future< V, E > &&head, Future< Vs, Es > &&... tail)
Create Future which will be ready when all futures are ready.
template<WhenPolicy P = WhenPolicy::LastFail, typename It , typename T = typename std::iterator_traits<It>::value_type>
auto WhenAny (It begin, std::size_t size)
Create Future that is ready when any of futures is ready.
template<WhenPolicy P = WhenPolicy::LastFail, typename It , typename T = typename std::iterator_traits<It>::value_type>
auto WhenAny (It begin, It end)
Create Future that is ready when any of futures is ready.
template<WhenPolicy P = WhenPolicy::LastFail, typename V , typename E , typename... Vs, typename Es >
Future< V, E > WhenAny (Future< V, E > &&head, Future< Vs, Es > &&... tail)
Create Future that is ready when any of futures is ready.
template<typename V , typename E = StopError>
Contract< V, E > MakeContract ()
Creates related future and promise.
template<typename V = Unit, typename E = StopError, typename... Args>
auto MakeFuture (Args &&... args)
template<typename E = StopError, typename Functor >
auto Run (const IExecutorPtr &e, Functor &&f)
Execute Callable functor via executor.
template<typename... V, typename... E>
detail::FutureAwaiter Await (Future< V, E > &... fs)
template<typename Iterator >
std::enable_if_t<!is_future_v< Iterator >, detail::FutureAwaiter > Await (Iterator begin, Iterator end)
template<typename Iterator >
std::enable_if_t<!is_future_v< Iterator >, detail::FutureAwaiter > Await (Iterator begin, std::size_t count)
IExecutorPtr MakeInline () noexcept
Get Inline executor singleton object.
IExecutorPtr MakeStrand (IExecutorPtr e)
Strand is the asynchronous analogue of a mutex.
template<typename Functor >
bool Submit (const IExecutorPtr &executor, Functor &&f)
Submit given functor for details.
IThreadFactoryPtr MakeThreadFactory (std::size_t cache=0)
IThreadFactoryPtr MakeThreadFactory (IThreadFactoryPtr base, std::string_view name)
IThreadFactoryPtr MakeThreadFactory (IThreadFactoryPtr base, std::size_t priority)
IThreadFactoryPtr MakeThreadFactory (IThreadFactoryPtr base, IFuncPtr acquire, IFuncPtr release)
IThreadPool * CurrentThreadPool () noexcept
IThreadPoolPtr MakeThreadPool (std::size_t threads=std::thread::hardware_concurrency(), IThreadFactoryPtr tf=MakeThreadFactory())
Create new ThreadPool object.
void SetFrequency (std::uint32_t freq)
Sets frequency with which fault will be injected.
void SetSleepTime (std::uint32_t ns)
Sets sleep time if sleep is used instead of yield for interrupting thread execution for fault injection.
void SetErrorCallback (LogCallback)
void SetInfoCallback (LogCallback)
template<typename Functor >
IFuncPtr MakeFunc (Functor &&f)
Create IFunc object from any Callable functor.
template<typename ObjectType , typename PtrType = ObjectType, typename... Args>
IntrusivePtr< PtrType > MakeIntrusive (Args &&... args)
template<typename T , typename U >
bool operator== (const IntrusivePtr< T > &lhs, const IntrusivePtr< U > &rhs) noexcept
template<typename T , typename U >
bool operator!= (const IntrusivePtr< T > &lhs, const IntrusivePtr< U > &rhs) noexcept
template<typename T , typename U >
bool operator== (const IntrusivePtr< T > &lhs, U *rhs) noexcept
template<typename T , typename U >
bool operator!= (const IntrusivePtr< T > &lhs, U *rhs) noexcept
template<typename T , typename U >
bool operator== (T *lhs, const IntrusivePtr< U > &rhs) noexcept
template<typename T , typename U >
bool operator!= (T *lhs, const IntrusivePtr< U > &rhs) noexcept
template<typename T >
bool operator== (const IntrusivePtr< T > &lhs, std::nullptr_t) noexcept
template<typename T >
bool operator== (std::nullptr_t, const IntrusivePtr< T > &rhs) noexcept
template<typename T >
bool operator!= (const IntrusivePtr< T > &lhs, std::nullptr_t) noexcept
template<typename T >
bool operator!= (std::nullptr_t, const IntrusivePtr< T > &rhs) noexcept
template<typename T >
bool operator< (const IntrusivePtr< T > &lhs, const IntrusivePtr< T > &rhs) noexcept
template<typename T >
constexpr bool Check () noexcept
Variables
template<typename Functor , typename... Arg>
constexpr bool is_invocable_v = detail::IsInvocable<Functor, Arg...>::Value
template<typename T >
constexpr bool is_result_v = detail::IsInstantiationOf<Result, T>::Value
template<typename T >
constexpr bool is_future_v = detail::IsInstantiationOf<Future, T>::Value
static Inline sInline
static LogCallback g_error_callback = nullptr
static LogCallback g_info_callback = nullptr
Typedef Documentation
Contract
template<typename V , typename E > using yaclib::Contract = typedef std::pair<Future<V, E>, Promise<V, E> >
Describes channel with future and promise.
Definition at line 11 of file contract.hpp.
future_error_t
template<typename T > using yaclib::future_error_t = typedef typename detail::InstantiationTypes<Future, T>::Error
Definition at line 37 of file type_traits.hpp.
future_value_t
template<typename T > using yaclib::future_value_t = typedef typename detail::InstantiationTypes<Future, T>::Value
Definition at line 34 of file type_traits.hpp.
head_t
template<typename... Args> using yaclib::head_t = typedef typename detail::Head<Args...>::Type
Definition at line 13 of file type_traits.hpp.
IExecutorPtr
using yaclib::IExecutorPtr = typedef IntrusivePtr<IExecutor>
Definition at line 39 of file executor.hpp.
IFuncPtr
using yaclib::IFuncPtr = typedef IntrusivePtr<IFunc>
Definition at line 22 of file func.hpp.
invoke_t
template<typename Functor , typename... Arg> using yaclib::invoke_t = typedef typename detail::Invoke<Functor, Arg...>::Type
Definition at line 19 of file type_traits.hpp.
IThreadFactoryPtr
using yaclib::IThreadFactoryPtr = typedef IntrusivePtr<IThreadFactory>
Definition at line 26 of file thread_factory.hpp.
IThreadPoolPtr
using yaclib::IThreadPoolPtr = typedef IntrusivePtr<IThreadPool>
Definition at line 42 of file thread_pool.hpp.
IThreadPtr
using yaclib::IThreadPtr = typedef IThread*
Definition at line 17 of file thread_factory.hpp.
LogCallback
using yaclib::LogCallback = typedef void (*)(std::string_view file, std::size_t line, std::string_view function, std::string_view condition, std::string_view message)
Definition at line 19 of file log.hpp.
result_error_t
template<typename T > using yaclib::result_error_t = typedef typename detail::InstantiationTypes<Result, T>::Error
Definition at line 28 of file type_traits.hpp.
result_value_t
template<typename T > using yaclib::result_value_t = typedef typename detail::InstantiationTypes<Result, T>::Value
Definition at line 25 of file type_traits.hpp.
Enumeration Type Documentation
ResultState
enum class yaclib::ResultState : char strong
Enumerator
Value
Exception
Error
Empty
Definition at line 15 of file result.hpp.
WhenPolicy
enum class yaclib::WhenPolicy strong
This Policy describe how When* algorithm interpret if Future will be fulfilled by error or exception.
None – Fail same as Ok FirstFail – save first fail LastFail – save last fail
Enumerator
None
FirstFail
LastFail
Definition at line 14 of file when_policy.hpp.
Function Documentation
Await() [1/3]
template<typename... V, typename... E> detail::FutureAwaiter yaclib::Await (Future< V, E > &... fs)
Definition at line 13 of file await.hpp.
Await() [2/3]
template<typename Iterator > std::enable_if_t<!is_future_v< Iterator >, detail::FutureAwaiter > yaclib::Await (Iterator begin, Iterator end)
Definition at line 18 of file await.hpp.
Await() [3/3]
template<typename Iterator > std::enable_if_t<!is_future_v< Iterator >, detail::FutureAwaiter > yaclib::Await (Iterator begin, std::size_t count)
Definition at line 23 of file await.hpp.
Check()
template<typename T > constexpr bool yaclib::Check () constexpr noexcept
Definition at line 40 of file type_traits.hpp.
CurrentThreadPool()
IThreadPool * yaclib::CurrentThreadPool () noexcept
Returns
Thread local pointer to the ThreadPool that owns the current thread nullptr if no ThreadPool owns the thread
Definition at line 138 of file thread_pool.cpp.
MakeContract()
template<typename V , typename E = StopError> Contract< V, E > yaclib::MakeContract ()
Creates related future and promise.
Returns
a
See also
Contract object with new future and promise
Definition at line 20 of file contract.hpp.
MakeFunc()
template<typename Functor > IFuncPtr yaclib::MakeFunc (Functor && f)
Create IFunc object from any Callable functor.
Parameters
f Callable object
Definition at line 30 of file func.hpp.
MakeFuture()
template<typename V = Unit, typename E = StopError, typename... Args> auto yaclib::MakeFuture (Args &&... args)
Definition at line 184 of file future.hpp.
MakeInline()
IExecutorPtr yaclib::MakeInline () noexcept
Get Inline executor singleton object.
This executor immediately executes given Callable object in the same OS thread without any overhead. So it always return false from Submit, we only call Call, no submit
Note
This object is useful as safe default executor value. See example.
auto task = [] {};
// Without inline executor:
IExecutorPtr executor = nullptr;
if (...) {
  executor = MakeThreadPool(4);
}
if (executor) {
  executor->Submit(task);
} else {
  a();
}
// With inline executor:
IExecutorPtr executor = MakeInlineExecutor();
if (...) {
  executor = MakeThreadPool(4);
}
executor->Submit(task);
Definition at line 27 of file inline.cpp.
References sInline.
MakeIntrusive()
template<typename ObjectType , typename PtrType = ObjectType, typename... Args> IntrusivePtr< PtrType > yaclib::MakeIntrusive (Args &&... args)
Definition at line 11 of file helper.hpp.
MakeStrand()
IExecutorPtr yaclib::MakeStrand (IExecutorPtr e)
Strand is the asynchronous analogue of a mutex.
It guarantees that the tasks scheduled for it will be executed strictly sequentially. Strand itself does not have its own threads, it decorates another executor and uses it to run its tasks.
Parameters
e executor to decorate
Returns
pointer to new Strand instance
Examples
simple.cpp, and strand.cpp.
Definition at line 78 of file strand.cpp.
Referenced by TEST().
MakeThreadFactory() [1/4]
IThreadFactoryPtr yaclib::MakeThreadFactory (IThreadFactoryPtr base, IFuncPtr acquire, IFuncPtr release)
Definition at line 366 of file thread_factory.cpp.
MakeThreadFactory() [2/4]
IThreadFactoryPtr yaclib::MakeThreadFactory (IThreadFactoryPtr base, std::size_t priority)
Definition at line 358 of file thread_factory.cpp.
MakeThreadFactory() [3/4]
IThreadFactoryPtr yaclib::MakeThreadFactory (IThreadFactoryPtr base, std::string_view name)
Definition at line 362 of file thread_factory.cpp.
MakeThreadFactory() [4/4]
IThreadFactoryPtr yaclib::MakeThreadFactory (std::size_t cache = 0)
Definition at line 350 of file thread_factory.cpp.
MakeThreadPool()
IThreadPoolPtr yaclib::MakeThreadPool (std::size_t threads = std::thread::hardware_concurrency(), IThreadFactoryPtr tf = MakeThreadFactory())
Create new ThreadPool object.
Parameters
threads the number of threads to create for this ThreadPool
tf thread factory to use for thread creation.
See also
IThreadFactory
Returns
intrusive pointer to the new ThreadPool
Examples
simple.cpp, strand.cpp, thread_pool.cpp, when_all.cpp, and when_any.cpp.
Definition at line 142 of file thread_pool.cpp.
Referenced by TEST().
operator!=() [1/5]
template<typename T , typename U > bool yaclib::operator!= (const IntrusivePtr< T > & lhs, const IntrusivePtr< U > & rhs) inline noexcept
Definition at line 69 of file intrusive_ptr.hpp.
operator!=() [2/5]
template<typename T > bool yaclib::operator!= (const IntrusivePtr< T > & lhs, std::nullptr_t) inline noexcept
Definition at line 103 of file intrusive_ptr.hpp.
operator!=() [3/5]
template<typename T , typename U > bool yaclib::operator!= (const IntrusivePtr< T > & lhs, U * rhs) inline noexcept
Definition at line 79 of file intrusive_ptr.hpp.
operator!=() [4/5]
template<typename T > bool yaclib::operator!= (std::nullptr_t , const IntrusivePtr< T > & rhs) inline noexcept
Definition at line 108 of file intrusive_ptr.hpp.
operator!=() [5/5]
template<typename T , typename U > bool yaclib::operator!= (T * lhs, const IntrusivePtr< U > & rhs) inline noexcept
Definition at line 89 of file intrusive_ptr.hpp.
operator<()
template<typename T > bool yaclib::operator< (const IntrusivePtr< T > & lhs, const IntrusivePtr< T > & rhs) inline noexcept
Definition at line 113 of file intrusive_ptr.hpp.
operator==() [1/5]
template<typename T , typename U > bool yaclib::operator== (const IntrusivePtr< T > & lhs, const IntrusivePtr< U > & rhs) inline noexcept
Definition at line 65 of file intrusive_ptr.hpp.
References yaclib::IntrusivePtr< T >::Get().
operator==() [2/5]
template<typename T > bool yaclib::operator== (const IntrusivePtr< T > & lhs, std::nullptr_t) inline noexcept
Definition at line 93 of file intrusive_ptr.hpp.
operator==() [3/5]
template<typename T , typename U > bool yaclib::operator== (const IntrusivePtr< T > & lhs, U * rhs) inline noexcept
Definition at line 74 of file intrusive_ptr.hpp.
operator==() [4/5]
template<typename T > bool yaclib::operator== (std::nullptr_t , const IntrusivePtr< T > & rhs) inline noexcept
Definition at line 98 of file intrusive_ptr.hpp.
operator==() [5/5]
template<typename T , typename U > bool yaclib::operator== (T * lhs, const IntrusivePtr< U > & rhs) inline noexcept
Definition at line 84 of file intrusive_ptr.hpp.
Run()
template<typename E = StopError, typename Functor > auto yaclib::Run (const IExecutorPtr & e, Functor && f)
Execute Callable functor via executor.
Parameters
e executor to be used to execute f and saved as callback executor for return Future
f functor to execute
Returns
Future corresponding f return value
Examples
simple.cpp, when_all.cpp, and when_any.cpp.
Definition at line 20 of file run.hpp.
References yaclib::IExecutor::Inline, yaclib::IExecutor::Submit(), yaclib::IExecutor::Tag(), YACLIB_ERROR, and YACLIB_INFO.
Referenced by CalculatorService::Double(), CalculatorService::Increment(), and TEST().
SetErrorCallback()
void yaclib::SetErrorCallback (LogCallback callback) inline
Definition at line 42 of file log.hpp.
SetFrequency()
void yaclib::SetFrequency (std::uint32_t freq)
Sets frequency with which fault will be injected.
Default is 16.
Definition at line 10 of file fault_config.cpp.
References yaclib::detail::Yielder::SetFrequency().
SetInfoCallback()
void yaclib::SetInfoCallback (LogCallback callback) inline
Definition at line 67 of file log.hpp.
SetSleepTime()
void yaclib::SetSleepTime (std::uint32_t ns)
Sets sleep time if sleep is used instead of yield for interrupting thread execution for fault injection.
Default is 200
Definition at line 16 of file fault_config.cpp.
References yaclib::detail::Yielder::SetSleepTime().
Submit()
template<typename Functor > bool yaclib::Submit (const IExecutorPtr & executor, Functor && f)
Submit given functor for details.
See also
Submit
This method creates ITask with one allocation and call Submit(ITask)
Parameters
f functor to execute
Returns
true if the task is accepted and scheduled for execution, false if the task is rejected
Examples
strand.cpp, and thread_pool.cpp.
Definition at line 19 of file submit.hpp.
References yaclib::detail::MakeUniqueTask(), and yaclib::IExecutor::Submit().
Referenced by TEST().
Wait() [1/3]
template<typename Event = detail::DefaultEvent, typename... V, typename... E> void yaclib::Wait (Future< V, E > &... fs)
Wait until Ready becomes true.
Parameters
fs one or more futures to wait
Definition at line 17 of file wait.hpp.
References yaclib::Future< V, E >::GetCore().
Wait() [2/3]
template<typename Event = detail::DefaultEvent, typename It > std::enable_if_t<!is_future_v< It >, void > yaclib::Wait (It begin, It end)
Wait until Ready becomes true.
Parameters
begin Iterator to futures to wait
end Iterator to futures to wait
Definition at line 28 of file wait.hpp.
Wait() [3/3]
template<typename Event = detail::DefaultEvent, typename It > void yaclib::Wait (It begin, std::size_t size)
Wait until Ready becomes true.
Parameters
begin Iterator to futures to wait
size count of futures to wait
Definition at line 41 of file wait.hpp.
WaitFor() [1/3]
template<typename Event = detail::MutexEvent, typename Rep , typename Period , typename... V, typename... E> bool yaclib::WaitFor (const std::chrono::duration< Rep, Period > & timeout_duration, Future< V, E > &... fs)
Wait until the specified timeout duration has elapsed or Ready becomes true.
The behavior is undefined if Valid is false before the call to this function. This function may block for longer than timeout_duration due to scheduling or resource contention delays.
Parameters
timeout_duration maximum duration to block for
fs futures to wait
Returns
The result of Ready upon exiting
Definition at line 23 of file wait_for.hpp.
References yaclib::Future< V, E >::GetCore().
WaitFor() [2/3]
template<typename Event = detail::MutexEvent, typename Rep , typename Period , typename Iterator > std::enable_if_t<!is_future_v< Iterator >, bool > yaclib::WaitFor (const std::chrono::duration< Rep, Period > & timeout_duration, Iterator begin, Iterator end)
Wait until the specified timeout duration has elapsed or Ready becomes true.
The behavior is undefined if Valid is false before the call to this function. This function may block for longer than timeout_duration due to scheduling or resource contention delays.
Parameters
timeout_duration maximum duration to block for
begin Iterator to futures to wait
end Iterator to futures to wait
Returns
The result of Ready upon exiting
Definition at line 38 of file wait_for.hpp.
WaitFor() [3/3]
template<typename Event = detail::MutexEvent, typename Rep , typename Period , typename Iterator > bool yaclib::WaitFor (const std::chrono::duration< Rep, Period > & timeout_duration, Iterator begin, std::size_t size)
Wait until the specified timeout duration has elapsed or Ready becomes true.
The behavior is undefined if Valid is false before the call to this function. This function may block for longer than timeout_duration due to scheduling or resource contention delays.
Parameters
timeout_duration maximum duration to block for
begin Iterator to futures to wait
size count of futures to wait
Returns
The result of Ready upon exiting
Definition at line 56 of file wait_for.hpp.
WaitUntil() [1/3]
template<typename Event = detail::MutexEvent, typename Clock , typename Duration , typename... V, typename... E> bool yaclib::WaitUntil (const std::chrono::time_point< Clock, Duration > & timeout_time, Future< V, E > &... fs)
Wait until specified time has been reached or Ready becomes true.
The behavior is undefined if Valid is false before the call to this function. This function may block for longer than until after timeout_time has been reached due to scheduling or resource contention delays.
Parameters
timeout_time maximum time point to block until
fs futures to wait
Returns
The result of Ready upon exiting
Definition at line 24 of file wait_until.hpp.
References yaclib::Future< V, E >::GetCore().
WaitUntil() [2/3]
template<typename Event = detail::MutexEvent, typename Clock , typename Duration , typename Iterator > std::enable_if_t<!is_future_v< Iterator >, bool > yaclib::WaitUntil (const std::chrono::time_point< Clock, Duration > & timeout_time, Iterator begin, Iterator end)
Wait until specified time has been reached or Ready becomes true.
The behavior is undefined if Valid is false before the call to this function. This function may block for longer than until after timeout_time has been reached due to scheduling or resource contention delays.
Parameters
timeout_time maximum time point to block until
begin Iterator to futures to wait
end Iterator to futures to wait
Returns
The result of Ready upon exiting
Definition at line 40 of file wait_until.hpp.
WaitUntil() [3/3]
template<typename Event = detail::MutexEvent, typename Clock , typename Duration , typename Iterator > bool yaclib::WaitUntil (const std::chrono::time_point< Clock, Duration > & timeout_time, Iterator begin, std::size_t size)
Wait until specified time has been reached or Ready becomes true.
The behavior is undefined if Valid is false before the call to this function. This function may block for longer than until after timeout_time has been reached due to scheduling or resource contention delays.
Parameters
timeout_time maximum time point to block until
begin Iterator to futures to wait
size count of futures to wait
Returns
The result of Ready upon exiting
Definition at line 59 of file wait_until.hpp.
WhenAll() [1/3]
template<WhenPolicy P = WhenPolicy::FirstFail, typename V , typename E , typename... Vs, typename... Es> auto yaclib::WhenAll (Future< V, E > && head, Future< Vs, Es > &&... tail)
Create Future which will be ready when all futures are ready.
Template Parameters
V type of value all passed futures
E type of error all passed futures
Parameters
head,tail one or more futures to combine
Returns
Future<std::array<T>>
Definition at line 58 of file when_all.hpp.
References FirstFail, yaclib::detail::AllCombinator< V, E, N, FutureValue >::Make(), and yaclib::detail::WhenImpl().
WhenAll() [2/3]
template<WhenPolicy P = WhenPolicy::FirstFail, typename It , typename T = typename std::iterator_traits<It>::value_type> auto yaclib::WhenAll (It begin, It end)
Create Future which will be ready when all futures are ready.
Template Parameters
It type of passed iterator
Parameters
begin,end the range of futures to combine
Returns
Future<std::vector<T>>
Definition at line 41 of file when_all.hpp.
References FirstFail, and WhenAll().
WhenAll() [3/3]
template<WhenPolicy P = WhenPolicy::FirstFail, typename It , typename T = typename std::iterator_traits<It>::value_type> auto yaclib::WhenAll (It begin, std::size_t size)
Create Future which will be ready when all futures are ready.
Template Parameters
It type of passed iterator
T type of all passed futures
Parameters
begin,size the range of futures to combine
Returns
Future<std::vector<T>>
Examples
when_all.cpp.
Definition at line 25 of file when_all.hpp.
References FirstFail, and yaclib::detail::WhenImpl().
Referenced by TEST(), and WhenAll().
WhenAny() [1/3]
template<WhenPolicy P = WhenPolicy::LastFail, typename V , typename E , typename... Vs, typename Es > Future< V, E > yaclib::WhenAny (Future< V, E > && head, Future< Vs, Es > &&... tail)
Create Future that is ready when any of futures is ready.
Template Parameters
P policy WhenAny errors
V type of value all passed futures
E type of error all passed futures
Parameters
head,tail one or more futures to combine
Returns
Future<T>
Definition at line 68 of file when_any.hpp.
References yaclib::detail::AnyCombinator< V, E, P >::Make(), and yaclib::detail::WhenImpl().
WhenAny() [2/3]
template<WhenPolicy P = WhenPolicy::LastFail, typename It , typename T = typename std::iterator_traits<It>::value_type> auto yaclib::WhenAny (It begin, It end)
Create Future that is ready when any of futures is ready.
Template Parameters
P policy WhenAny errors
It type of passed iterator
T type of all passed futures
Parameters
begin,end the range of futures to combine
Returns
Future<T>
Definition at line 51 of file when_any.hpp.
WhenAny() [3/3]
template<WhenPolicy P = WhenPolicy::LastFail, typename It , typename T = typename std::iterator_traits<It>::value_type> auto yaclib::WhenAny (It begin, std::size_t size)
Create Future that is ready when any of futures is ready.
Template Parameters
P policy WhenAny errors
It type of passed iterator
T type of all passed futures
Parameters
begin,size the range of futures to combine
Returns
Future<T>
Examples
when_any.cpp.
Definition at line 26 of file when_any.hpp.
References yaclib::detail::AnyCombinator< V, E, P >::Make(), and yaclib::detail::WhenImpl().
Referenced by TEST().
Variable Documentation
g_error_callback
LogCallback yaclib::g_error_callback = nullptr static
Definition at line 11 of file log_error.cpp.
g_info_callback
LogCallback yaclib::g_info_callback = nullptr static
Definition at line 11 of file log_info.cpp.
is_future_v
template<typename T > constexpr bool yaclib::is_future_v = detail::IsInstantiationOf<Future, T>::Value inline constexpr
Definition at line 31 of file type_traits.hpp.
is_invocable_v
template<typename Functor , typename... Arg> constexpr bool yaclib::is_invocable_v = detail::IsInvocable<Functor, Arg...>::Value inline constexpr
Definition at line 16 of file type_traits.hpp.
is_result_v
template<typename T > constexpr bool yaclib::is_result_v = detail::IsInstantiationOf<Result, T>::Value inline constexpr
Definition at line 22 of file type_traits.hpp.
sInline
Inline yaclib::sInline static
Definition at line 25 of file inline.cpp.
Referenced by MakeInline().