YACLib: yaclib::detail::AtomicCounter< CounterBase, Deleter > Struct Template Reference
yaclib::detail::AtomicCounter< CounterBase, Deleter > Struct Template Reference
#include <atomic_counter.hpp>
Public Member Functions
template<typename... Args>
AtomicCounter (std::size_t n, Args &&... args)
void IncRef () noexcept final
void DecRef () noexcept final
std::size_t GetRef () const noexcept
bool SubEqual (std::size_t n) noexcept
Public Attributes
yaclib_std::atomic_size_t count
Detailed Description
template<typename CounterBase, typename Deleter = detail::DefaultDeleter>
struct yaclib::detail::AtomicCounter< CounterBase, Deleter >
Definition at line 19 of file atomic_counter.hpp.
Constructor & Destructor Documentation
AtomicCounter()
template<typename CounterBase , typename Deleter = detail::DefaultDeleter> template<typename... Args> yaclib::detail::AtomicCounter< CounterBase, Deleter >::AtomicCounter (std::size_t n, Args &&... args) inline
Definition at line 21 of file atomic_counter.hpp.
Member Function Documentation
DecRef()
template<typename CounterBase , typename Deleter = detail::DefaultDeleter> void yaclib::detail::AtomicCounter< CounterBase, Deleter >::DecRef () inline final noexcept
Definition at line 28 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::count.
GetRef()
template<typename CounterBase , typename Deleter = detail::DefaultDeleter> std::size_t yaclib::detail::AtomicCounter< CounterBase, Deleter >::GetRef () const inline noexcept
Definition at line 41 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::count.
Referenced by yaclib::detail::FutureAwaiter::await_ready().
IncRef()
template<typename CounterBase , typename Deleter = detail::DefaultDeleter> void yaclib::detail::AtomicCounter< CounterBase, Deleter >::IncRef () inline final noexcept
Definition at line 24 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::count.
SubEqual()
template<typename CounterBase , typename Deleter = detail::DefaultDeleter> bool yaclib::detail::AtomicCounter< CounterBase, Deleter >::SubEqual (std::size_t n) inline noexcept
Definition at line 46 of file atomic_counter.hpp.
References yaclib::detail::AtomicCounter< CounterBase, Deleter >::count.
Referenced by yaclib::detail::FutureAwaiter::await_suspend(), and yaclib::detail::FutureAwaiter::FutureAwaiter().
Member Data Documentation
count
template<typename CounterBase , typename Deleter = detail::DefaultDeleter> yaclib_std::atomic_size_t yaclib::detail::AtomicCounter< CounterBase, Deleter >::count
Definition at line 50 of file atomic_counter.hpp.
Referenced by yaclib::detail::AtomicCounter< CounterBase, Deleter >::DecRef(), yaclib::detail::AtomicCounter< CounterBase, Deleter >::GetRef(), yaclib::detail::AtomicCounter< CounterBase, Deleter >::IncRef(), and yaclib::detail::AtomicCounter< CounterBase, Deleter >::SubEqual().
The documentation for this struct was generated from the following file:
include/yaclib/util/detail/atomic_counter.hpp