YACLib: yaclib::detail::PromiseType< V, E > Struct Template Reference
yaclib::detail::PromiseType< V, E > Struct Template Reference
#include <promise_type.hpp>
Public Types
using Base = AtomicCounter< ResultCore< V, E >, CoroutineDeleter >
Public Types inherited from yaclib::detail::InlineCore
enum class State {
Empty = 0 , HasResult , HasCallback , HasCallbackInline ,
HasAsyncCallback , HasWait , HasStop
}
Public Member Functions
PromiseType ()
Future< V, E > get_return_object ()
yaclib_std::suspend_never initial_suspend () noexcept
Destroy< V, E > final_suspend () noexcept
void return_value (const V &value) noexcept(std::is_nothrow_copy_constructible_v< V >)
void return_value (V &&value) noexcept(std::is_nothrow_move_constructible_v< V >)
void unhandled_exception () noexcept
Public Member Functions inherited from yaclib::detail::AtomicCounter< ResultCore< V, E >, CoroutineDeleter >
AtomicCounter (std::size_t n, Args &&... args)
void IncRef () noexcept final
void DecRef () noexcept final
std::size_t GetRef () const noexcept
bool SubEqual (std::size_t n) noexcept
Public Member Functions inherited from yaclib::detail::ResultCore< V, E >
ResultCore () noexcept
template<typename... Args>
ResultCore (Args &&... args)
template<typename T >
void Set (T &&value) noexcept
void SetStop () final
Result< V, E > & Get () noexcept
Public Member Functions inherited from yaclib::detail::BaseCore
BaseCore (State s) noexcept
void SetExecutor (IExecutorPtr executor) noexcept
const IExecutorPtr & GetExecutor () const noexcept
void SetCallback (BaseCore &callback) noexcept
void SetCallbackInline (InlineCore &callback, bool async=false) noexcept
bool SetWait (IRef &callback) noexcept
bool ResetWait () noexcept
virtual void SetStop ()=0
void Stop () noexcept
bool Empty () const noexcept
bool Alive () const noexcept
Public Member Functions inherited from yaclib::detail::InlineCore
void Call () noexcept override
void Cancel () noexcept override
virtual void CallInline (InlineCore &, State) noexcept
virtual void Cancel () noexcept=0
virtual void Call () noexcept=0
Public Member Functions inherited from yaclib::IRef
virtual void IncRef () noexcept=0
Increments reference counter.
virtual void DecRef () noexcept=0
Decrements reference counter.
virtual ~IRef ()=default
Additional Inherited Members
Public Attributes inherited from yaclib::detail::AtomicCounter< ResultCore< V, E >, CoroutineDeleter >
yaclib_std::atomic_size_t count
Public Attributes inherited from yaclib::detail::Node
Node * next = nullptr
Protected Member Functions inherited from yaclib::detail::BaseCore
void Submit () noexcept
void Cancel () noexcept final
Protected Attributes inherited from yaclib::detail::BaseCore
yaclib_std::atomic< State > _state
IntrusivePtr< ITask > _caller
IExecutorPtr _executor
IntrusivePtr< IRef > _callback
Detailed Description
template<typename V, typename E>
struct yaclib::detail::PromiseType< V, E >
Definition at line 38 of file promise_type.hpp.
Member Typedef Documentation
Base
template<typename V , typename E > using yaclib::detail::PromiseType< V, E >::Base = AtomicCounter<ResultCore<V, E>, CoroutineDeleter>
Definition at line 39 of file promise_type.hpp.
Constructor & Destructor Documentation
PromiseType()
template<typename V , typename E > yaclib::detail::PromiseType< V, E >::PromiseType () inline
Definition at line 40 of file promise_type.hpp.
Member Function Documentation
final_suspend()
template<typename V , typename E > Destroy< V, E > yaclib::detail::PromiseType< V, E >::final_suspend () inline noexcept
Definition at line 51 of file promise_type.hpp.
get_return_object()
template<typename V , typename E > Future< V, E > yaclib::detail::PromiseType< V, E >::get_return_object () inline
Definition at line 43 of file promise_type.hpp.
initial_suspend()
template<typename V , typename E > yaclib_std::suspend_never yaclib::detail::PromiseType< V, E >::initial_suspend () inline noexcept
Definition at line 47 of file promise_type.hpp.
return_value() [1/2]
template<typename V , typename E > void yaclib::detail::PromiseType< V, E >::return_value (const V & value) inline noexcept
Definition at line 55 of file promise_type.hpp.
References yaclib::detail::ResultCore< V, E >::Set().
return_value() [2/2]
template<typename V , typename E > void yaclib::detail::PromiseType< V, E >::return_value (V && value) inline noexcept
Definition at line 59 of file promise_type.hpp.
References yaclib::detail::ResultCore< V, E >::Set().
unhandled_exception()
template<typename V , typename E > void yaclib::detail::PromiseType< V, E >::unhandled_exception () inline noexcept
Definition at line 63 of file promise_type.hpp.
References yaclib::detail::ResultCore< V, E >::Set().
The documentation for this struct was generated from the following file:
include/yaclib/coroutine/detail/promise_type.hpp