YACLib: yaclib::detail::AtomicBase< T, Atomic, bool > Struct Template Reference
yaclib::detail::AtomicBase< T, Atomic, bool > Struct Template Reference
#include <atomic_base.hpp>
Public Member Functions
bool is_lock_free () const volatile noexcept
bool is_lock_free () const noexcept
void store (T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
void store (T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
T load (std::memory_order order=std::memory_order_seq_cst) const volatile noexcept
T load (std::memory_order order=std::memory_order_seq_cst) const noexcept
operator T () const volatile noexcept
operator T () const noexcept
T exchange (T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
T exchange (T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order success, std::memory_order failure) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order success, std::memory_order failure) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order success, std::memory_order failure) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order success, std::memory_order failure) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
AtomicBase () noexcept=default
constexpr AtomicBase (T desired) noexcept
AtomicBase (const AtomicBase &)=delete
AtomicBase & operator= (const AtomicBase &)=delete
AtomicBase & operator= (const AtomicBase &) volatile=delete
Protected Attributes
Atomic _impl
Detailed Description
template<typename T, typename Atomic, bool = std::is_integral<T>::value && !std::is_same<T, bool>::value>
struct yaclib::detail::AtomicBase< T, Atomic, bool >
Definition at line 14 of file atomic_base.hpp.
Constructor & Destructor Documentation
AtomicBase() [1/3]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> yaclib::detail::AtomicBase< T, Atomic, bool >::AtomicBase () default noexcept
AtomicBase() [2/3]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> constexpr yaclib::detail::AtomicBase< T, Atomic, bool >::AtomicBase (T desired) inline constexpr noexcept
Definition at line 105 of file atomic_base.hpp.
AtomicBase() [3/3]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> yaclib::detail::AtomicBase< T, Atomic, bool >::AtomicBase (const AtomicBase< T, Atomic, bool > &) delete
Member Function Documentation
compare_exchange_strong() [1/4]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 98 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong(), and YACLIB_INJECT_FAULT.
compare_exchange_strong() [2/4]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Definition at line 92 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong(), and YACLIB_INJECT_FAULT.
compare_exchange_strong() [3/4]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong (T & expected, T desired, std::memory_order success, std::memory_order failure) inline noexcept
Definition at line 76 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong(), and YACLIB_INJECT_FAULT.
compare_exchange_strong() [4/4]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong (T & expected, T desired, std::memory_order success, std::memory_order failure) volatile inline noexcept
Definition at line 70 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong(), and YACLIB_INJECT_FAULT.
Referenced by yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong().
compare_exchange_weak() [1/4]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 87 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak(), and YACLIB_INJECT_FAULT.
compare_exchange_weak() [2/4]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Definition at line 81 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak(), and YACLIB_INJECT_FAULT.
compare_exchange_weak() [3/4]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak (T & expected, T desired, std::memory_order success, std::memory_order failure) inline noexcept
Definition at line 65 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak(), and YACLIB_INJECT_FAULT.
compare_exchange_weak() [4/4]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak (T & expected, T desired, std::memory_order success, std::memory_order failure) volatile inline noexcept
Definition at line 59 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak(), and YACLIB_INJECT_FAULT.
Referenced by yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak().
exchange() [1/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> T yaclib::detail::AtomicBase< T, Atomic, bool >::exchange (T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 54 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::exchange(), and YACLIB_INJECT_FAULT.
exchange() [2/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> T yaclib::detail::AtomicBase< T, Atomic, bool >::exchange (T desired, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Definition at line 49 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::exchange(), and YACLIB_INJECT_FAULT.
Referenced by yaclib::detail::AtomicBase< T, Atomic, bool >::exchange().
is_lock_free() [1/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::is_lock_free () const inline noexcept
Definition at line 19 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, and yaclib::detail::AtomicBase< T, Atomic, bool >::is_lock_free().
is_lock_free() [2/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> bool yaclib::detail::AtomicBase< T, Atomic, bool >::is_lock_free () const volatile inline noexcept
Definition at line 15 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, and yaclib::detail::AtomicBase< T, Atomic, bool >::is_lock_free().
Referenced by yaclib::detail::AtomicBase< T, Atomic, bool >::is_lock_free().
load() [1/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> T yaclib::detail::AtomicBase< T, Atomic, bool >::load (std::memory_order order = std::memory_order_seq_cst) const inline noexcept
Definition at line 36 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::load(), and YACLIB_INJECT_FAULT.
load() [2/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> T yaclib::detail::AtomicBase< T, Atomic, bool >::load (std::memory_order order = std::memory_order_seq_cst) const volatile inline noexcept
Definition at line 31 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::load(), and YACLIB_INJECT_FAULT.
Referenced by yaclib::detail::AtomicBase< T, Atomic, bool >::load(), and yaclib::detail::AtomicBase< T, Atomic, bool >::operator T().
operator T() [1/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> yaclib::detail::AtomicBase< T, Atomic, bool >::operator T () const inline noexcept
Definition at line 45 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::load().
operator T() [2/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> yaclib::detail::AtomicBase< T, Atomic, bool >::operator T () const volatile inline noexcept
Definition at line 41 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::load().
operator=() [1/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> AtomicBase & yaclib::detail::AtomicBase< T, Atomic, bool >::operator= (const AtomicBase< T, Atomic, bool > &) volatile delete
operator=() [2/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> AtomicBase & yaclib::detail::AtomicBase< T, Atomic, bool >::operator= (const AtomicBase< T, Atomic, bool > &) delete
store() [1/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> void yaclib::detail::AtomicBase< T, Atomic, bool >::store (T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 27 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::store(), and YACLIB_INJECT_FAULT.
store() [2/2]
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> void yaclib::detail::AtomicBase< T, Atomic, bool >::store (T desired, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Definition at line 23 of file atomic_base.hpp.
References yaclib::detail::AtomicBase< T, Atomic, bool >::_impl, yaclib::detail::AtomicBase< T, Atomic, bool >::store(), and YACLIB_INJECT_FAULT.
Referenced by yaclib::detail::AtomicBase< T, Atomic, bool >::store().
Member Data Documentation
_impl
template<typename T , typename Atomic , bool = std::is_integral<T>::value && !std::is_same<T, bool>::value> Atomic yaclib::detail::AtomicBase< T, Atomic, bool >::_impl protected
Definition at line 113 of file atomic_base.hpp.
Referenced by yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_strong(), yaclib::detail::AtomicBase< T, Atomic, bool >::compare_exchange_weak(), yaclib::detail::AtomicBase< T, Atomic, bool >::exchange(), yaclib::detail::AtomicBase< T, Atomic, true >::fetch_add(), yaclib::detail::AtomicBase< T, Atomic, true >::fetch_and(), yaclib::detail::AtomicBase< T, Atomic, true >::fetch_or(), yaclib::detail::AtomicBase< T, Atomic, true >::fetch_sub(), yaclib::detail::AtomicBase< T, Atomic, true >::fetch_xor(), yaclib::detail::AtomicBase< T, Atomic, bool >::is_lock_free(), yaclib::detail::AtomicBase< T, Atomic, bool >::load(), and yaclib::detail::AtomicBase< T, Atomic, bool >::store().
The documentation for this struct was generated from the following file:
include/yaclib/fault/detail/atomic/atomic_base.hpp